# Generated by Django 3.0.7 on 2021-04-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20210410_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptrequest',
            old_name='adopted',
            new_name='adopter',
        ),
    ]
